from __future__ import annotations

import csv
import subprocess
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
STATUS_PATH = PROJECT_ROOT / "docs" / "repository-status.md"
DATA_DIR = PROJECT_ROOT / "data" / "raw"


def run_git(*args: str) -> str:
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=PROJECT_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return "unavailable"
    return completed.stdout.strip() or "unavailable"


def discover_dataset() -> tuple[str, int, int, list[str]]:
    csv_files = sorted(DATA_DIR.glob("*.csv"))
    if not csv_files:
        return ("No dataset committed", 0, 0, [])

    dataset_path = csv_files[0]
    with dataset_path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.reader(handle)
        try:
            header = next(reader)
        except StopIteration:
            return (str(dataset_path.relative_to(PROJECT_ROOT)), 0, 0, [])

        row_count = sum(1 for _ in reader)

    return (
        str(dataset_path.relative_to(PROJECT_ROOT)),
        row_count,
        len(header),
        header,
    )


def build_status_markdown() -> str:
    dataset_path, row_count, column_count, header = discover_dataset()
    remote = run_git("remote", "get-url", "origin")
    branch = run_git("branch", "--show-current")
    header_preview = ", ".join(header[:8]) if header else "Unavailable"

    return "\n".join(
        [
            "# Repository Status",
            "",
            "_This file is generated by `scripts/sync_project_docs.py`. Do not edit it manually._",
            "",
            "## GitHub",
            f"- Remote: `{remote}`",
            f"- Active branch: `{branch}`",
            "",
            "## Dataset",
            f"- Committed CSV: `{dataset_path}`",
            f"- Row count: `{row_count}`",
            f"- Column count: `{column_count}`",
            f"- Header preview: `{header_preview}`",
            "",
            "## Docs Freshness",
            "- Generated docs are refreshed by `.githooks/pre-commit` before commits.",
            "- CI reruns the generator and fails if `docs/repository-status.md` is stale.",
            "- Manual Markdown pages must still be updated when project behavior or workflow changes.",
            "",
        ]
    )


def main() -> None:
    STATUS_PATH.write_text(build_status_markdown(), encoding="utf-8")


if __name__ == "__main__":
    main()
