from __future__ import annotations

import csv
import subprocess
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
STATUS_PATH = PROJECT_ROOT / "docs" / "repository-status.md"
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"
ANFIS_WEIGHTS_PATH = PROJECT_ROOT / "models" / "anfis_weights.json"


def run_git(*args: str) -> str:
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=PROJECT_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return "unavailable"
    return completed.stdout.strip() or "unavailable"


def discover_dataset() -> tuple[str, int, int, list[str]]:
    csv_files = sorted(RAW_DATA_DIR.glob("*.csv"))
    if not csv_files:
        return ("No dataset committed", 0, 0, [])

    dataset_path = csv_files[0]
    with dataset_path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.reader(handle)
        try:
            header = next(reader)
        except StopIteration:
            return (str(dataset_path.relative_to(PROJECT_ROOT)), 0, 0, [])

        row_count = sum(1 for _ in reader)

    return (
        str(dataset_path.relative_to(PROJECT_ROOT)),
        row_count,
        len(header),
        header,
    )


def discover_processed_dataset() -> tuple[str, int, int, list[str]]:
    csv_files = sorted(PROCESSED_DATA_DIR.glob("*.csv"))
    if not csv_files:
        return ("No processed dataset committed", 0, 0, [])

    dataset_path = csv_files[0]
    with dataset_path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.reader(handle)
        try:
            header = next(reader)
        except StopIteration:
            return (str(dataset_path.relative_to(PROJECT_ROOT)), 0, 0, [])

        row_count = sum(1 for _ in reader)

    return (
        str(dataset_path.relative_to(PROJECT_ROOT)),
        row_count,
        len(header),
        header,
    )


def build_status_markdown() -> str:
    dataset_path, row_count, column_count, header = discover_dataset()
    processed_path, processed_row_count, processed_column_count, processed_header = discover_processed_dataset()
    remote = run_git("remote", "get-url", "origin")
    branch = run_git("branch", "--show-current")
    header_preview = ", ".join(header[:8]) if header else "Unavailable"
    processed_header_preview = ", ".join(processed_header[:8]) if processed_header else "Unavailable"
    anfis_status = "present" if ANFIS_WEIGHTS_PATH.exists() else "missing"
    hooks_path = run_git("config", "--get", "core.hooksPath")

    return "\n".join(
        [
            "# Repository Status",
            "",
            "_This file is generated by `scripts/sync_project_docs.py`. Do not edit it manually._",
            "",
            "## GitHub",
            f"- Remote: `{remote}`",
            f"- Active branch: `{branch}`",
            "",
            "## Dataset",
            f"- Raw CSV: `{dataset_path}`",
            f"- Raw row count: `{row_count}`",
            f"- Raw column count: `{column_count}`",
            f"- Raw header preview: `{header_preview}`",
            f"- Processed CSV: `{processed_path}`",
            f"- Processed row count: `{processed_row_count}`",
            f"- Processed column count: `{processed_column_count}`",
            f"- Processed header preview: `{processed_header_preview}`",
            "",
            "## Models",
            f"- ANFIS weights: `{ANFIS_WEIGHTS_PATH.relative_to(PROJECT_ROOT)}` ({anfis_status})",
            "",
            "## Docs Freshness",
            f"- Git hooks path: `{hooks_path}`",
            "- Generated docs are refreshed by `.githooks/pre-commit` before commits.",
            "- Run `python3 scripts/sync_project_docs.py` locally whenever repository facts change.",
            "- Run `python3 scripts/build_processed_dataset.py` locally when the preprocessing logic changes.",
            "- Run `python3 scripts/train_anfis.py` locally whenever the committed hybrid weights need retraining.",
            "- Manual Markdown pages must still be updated when project behavior or workflow changes.",
            "",
        ]
    )


def main() -> None:
    STATUS_PATH.write_text(build_status_markdown(), encoding="utf-8")


if __name__ == "__main__":
    main()
